name: camjam
description: "Posing game for fun."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.2
  firebase_core: ^3.10.1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  crypto: ^3.0.6
  shared_preferences: ^2.4.0
  firebase_storage: ^12.4.1
  flutter_svg: ^2.0.17
  animated_splash_screen: ^1.3.0
  lottie: ^3.2.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/dummy.png
    - lib/assets/logo-big.png
    - lib/assets/logo-small.png
    - lib/assets/avatar_0.png
    - lib/assets/avatar_1.png
    - lib/assets/avatar_2.png
    - lib/assets/avatar_3.png
    - lib/assets/avatar_4.png
    - lib/assets/avatar_5.png
    - lib/assets/avatar_6.png
    - lib/assets/currency_icon.png
    - lib/assets/question_icon.png
    - lib/assets/heart_icon.png
    - lib/assets/heart_icon_purple.png
    - lib/assets/heart_icon_outline.png
    - lib/assets/heart_icon_inline.png
    - lib/assets/splash_animation.json
    - lib/assets/heart_animation.json
    - lib/assets/yagmur.png
    - lib/assets/mucahit.png
